# Generated by Django 2.2.10 on 2021-09-04 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('opisanie', models.CharField(max_length=900)),
                ('date_of_start', models.DateTimeField(blank=True, null=True)),
                ('date_of_end', models.DateTimeField(blank=True, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question_tekst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('question_answer', models.CharField(max_length=1000)),
                ('opros_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_for_opros', to='app.Opros')),
            ],
        ),
        migrations.CreateModel(
            name='Question_1variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('answer_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer_3', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer_4', models.CharField(blank=True, max_length=1000, null=True)),
                ('opros_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_1variant', to='app.Opros')),
            ],
        ),
    ]
