# Generated by Django 2.2.10 on 2021-09-04 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210904_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_1variant',
            name='opros_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_1variant', to='app.Opros'),
        ),
        migrations.AlterField(
            model_name='question_tekst',
            name='opros_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_for_opros', to='app.Opros'),
        ),
    ]
