# Generated by Django 2.2.10 on 2021-09-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210904_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_1variant',
            new_name='Question_variant',
        ),
    ]
