# Generated by Django 2.2.10 on 2021-09-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210904_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_variant',
            old_name='answer_1',
            new_name='variant_1',
        ),
        migrations.RenameField(
            model_name='question_variant',
            old_name='answer_2',
            new_name='variant_2',
        ),
        migrations.RenameField(
            model_name='question_variant',
            old_name='answer_3',
            new_name='variant_3',
        ),
        migrations.RenameField(
            model_name='question_variant',
            old_name='answer_4',
            new_name='variant_4',
        ),
        migrations.RenameField(
            model_name='question_variant',
            old_name='question_text',
            new_name='vopros',
        ),
    ]
