# Generated by Django 2.2.10 on 2021-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210904_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_variant',
            name='mnogo',
            field=models.BooleanField(default=False),
        ),
    ]
