# Generated by Django 2.2.10 on 2021-09-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_question_variant_mnogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answer_for_tekst_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer_variant_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer_variant_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer_variant_3', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer_variant_4', models.CharField(blank=True, max_length=1000, null=True)),
                ('opros_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opros_id', to='app.Opros')),
                ('question_tekst_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_tekst_id', to='app.Question_tekst')),
                ('question_variant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_variant_id', to='app.Question_variant')),
            ],
        ),
    ]
